# Generated by Django 4.2 on 2023-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_comment_comment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=' ', upload_to='posts'),
            preserve_default=False,
        ),
    ]
